platform:ios,'8.0'
target 'LaiFengLoan' do
pod 'MJRefresh'
pod 'AFNetworking'
pod 'MBProgressHUD'
pod 'IQKeyboardManager'
pod 'Masonry'
pod 'SDWebImage'
pod 'MJExtension'
pod 'SDCycleScrollView','~>1.75'
pod 'DateTools'
end
